### ISSUE TITLE
warn: "command 'extension.RNReload' not found"

### ISSUE THREAD

**Issue by FakeYou** [lucasbento/react-native-actions#5] opened 2017-10-19 07:02 UTC
Cool looking extension, this could be really helpful. But I am having some issues with getting it to work properly.

I have a project with a folder with a react-native app inside it. If I open the project itself and try one of the command I get this error:

```
command 'extension.RNReload' not found
```

If I open the directory where the app itself is in vscode and try a command it does work. 

Any idea how to get it working from the root project folder?

**Comment by lucasbento** [comment] 2017-10-19 08:40
Hey @FakeYou, that's odd, how does your project structure look like and what version are you using on the extension?

**Comment by FakeYou** [comment] 2017-10-19 08:48
my project structure looks like this

```
project <= root
|-- README.md
|-- docs
|   |-- doc.md
|   `-- other.md
|-- app <= react-native app
|   |-- node_modules
|   |-- src
|   |-- package.json
|   |-- index.ios.js
|   `-- index.android.js
`-- other stuff
    `-- something.txt
```

I just installed the extensions, so I must be using version 0.0.11

**Comment by lucasbento** [comment] 2017-10-19 08:59
@FakeYou: ah, I guess I know what the problem is:

The extension uses https://github.com/lucasbento/is-package-dep to get the closest `package.json` upwards and check if the project has react-native, it's not checking into other directories, tried it here and got sorta the same bug. I guess it's better to check into other directories inside of the project as well.

**Comment by lucasbento** [comment] 2017-10-19 10:35
@FakeYou: just released `0.0.12` with `0.1.1` of https://github.com/lucasbento/is-package-dep that includes a fix for it, can you update the extension to check if it runs okay for you?

To update:
![image](https://user-images.githubusercontent.com/6207220/31767018-ea635e1e-b4c9-11e7-85e4-a671fb50a7ab.png)

Thanks!

**Comment by FakeYou** [comment] 2017-10-19 14:49
@lucasbento It works 👍 .

It didn't work at first but after I few minutes of investigating I found out there was a lost `package.json` in my home directory. This made `is-package-dep` think we weren't in a React Native project. Maybe you should limit the upwards search to the folder that is currently open in vscode?

Anyway thanks for the update its working great now!

**Comment by lucasbento** [comment] 2017-10-19 15:24
@FakeYou: interesting, glad it worked!

Gonna think about a way to solve that problem with `is-package-dep`, thanks!

I'll close this since it's fixed, thank you for reporting it.

**Closed by lucasbento** 2017-10-19 15:24 UTC
Labels: bug, waiting-for-response
